call pathogen#infect()
call pathogen#helptags()

syntax on
syntax enable

" General settings
set nocompatible
scriptencoding utf8
set encoding=utf8
set number
set showmatch
set visualbell

" Automaticaly word wrap and insert new line
set textwidth=0
set nowrap

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set noexpandtab
set smarttab
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4


" Some settings
"set list extends:>,precedes:<

" Invisible character symbol
set listchars=tab:▸\ ,eol:¬
"set showbreak=➤
set showbreak=…

" let configs
let mapleader=","

" Airline
set t_Co=256
set laststatus=2
let g:airline_powerline_fonts = 1
"let g:airline#extensions#branch#enabled=1
"let g:airline#extensions#hunks#enabled=0

"let g:airline_theme="badwolf"
"let g:airline_section_b = '%{strftime("%c")}'
"let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#tabline#left_sep=' '
"let g:airline#extensions#tabline#left_alt_sep='|'

" Emmet - Enable in different mode
let g:user_emmet_mode="a"    "enable all function in all mode.

" Emmet - Enable just for html/css files
let g:user_emmet_install_global = 0

if has("autocmd")
	" Enable filetype detection
	filetype plugin indent on
	filetype plugin on
	autocmd FileType html,css EmmetInstall

	" Automatically apply any changes in vimrc
	"autocmd BufWritePost .vimrc tabe $MYVIMRC
endif

" Load custom settings
source ~/.vim/variables.vim
exec ":source " . MYVIMMAP
source ~/.vim/startup/color.vim

" My settings
set hidden

" Vertical window split on right side
set splitright

" Toggle paste mode
set pastetoggle=<F2>

" I use ore more modern way to loss data, I use GIT
set nobackup
set noswapfile

" correction
iabbr ture true
iabbr flase false

if &t_Co > 2 || has("gui_running")
	source ~/.vim/gvimrc
endif
