call pathogen#infect()
call pathogen#helptags()

syntax on
syntax enable

" General settings
set nocompatible
scriptencoding utf8
set encoding=utf8
set relativenumber
set showmatch
set visualbell

" Automaticaly word wrap and insert new line
set textwidth=0
set nowrap

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set noexpandtab
set smarttab
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4


" Some settings
"set list extends:>,precedes:<

" Invisible character symbol
set listchars=tab:▸\ ,eol:¬
"set showbreak=➤
set showbreak=…

" let configs
"let mapleader=","

" Airline
set t_Co=256
set laststatus=2
let g:airline_powerline_fonts = 1
"let g:airline#extensions#branch#enabled=1
"let g:airline#extensions#hunks#enabled=0

"let g:airline_theme="badwolf"
"let g:airline_section_b = '%{strftime("%c")}'
"let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#tabline#left_sep=' '
"let g:airline#extensions#tabline#left_alt_sep='|'


" Load custom settings
source ~/.vim/variables.vim
source ~/.vim/functions.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/color.vim

if has("autocmd")
	" Enable filetype detection
	filetype plugin on
	"filetype plugin indent on

	" Automatically apply any changes in vimrc
	"autocmd BufWritePost .vimrc tabe $MYVIMRC
endif

" My settings
set hidden

" Vertical window split on right side
set splitright

" Toggle paste mode
" set pastetoggle=<F2>

" I use ore more modern way to loss data, I use GIT
set nobackup
set noswapfile

" correction
iabbr ture true
iabbr flase false
iabbr fasle false

if has("gui_running")
	source ~/.vim/gvimrc
endif

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
