" Of course
set nocompatible

" Append +=
" Ask variable's value -> set variable?

if exists('cliclick')
	source ~/.vim/robot_plugins.vim
elseif exists('weak_mode')
	source ~/.vim/modes/weak_mode.vim
elseif exists('book')
	source ~/.vim/modes/book.vim
elseif exists('facebook')
	source ~/.vim/modes/facebook.vim
else
	source ~/.vim/plugins.vim
endif

command! -nargs=+ Silent execute 'silent <args>' | redraw!

" Might be useful when u have some stupid highlight won't go away
" :call clearmatches()

syntax on
syntax enable

" General settings
scriptencoding utf8
set encoding=utf8
set showmatch
set visualbell
set backspace=indent,eol,start
set mouse=a

"set nofoldenable    " disable folding
set foldmethod=manual
"set foldmethod=marker
"set foldlevel=1
set viewdir=~/.vimview

" Automaticaly word wrap and insert new line
set textwidth=0
set nowrap

set number
set relativenumber
set cursorline
set cursorcolumn
"set colorcolumn=81

set hlsearch
set smartcase
set ignorecase
set incsearch

" Tab configs
set autoindent
set smarttab
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
" On pressing tab, insert spaces or tab (noexpandtab = tab, expandtab = spaces)
" after change the config use `:retab` to replace tabs
set expandtab

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path=*,**

" Display all matching files when we tab complete
set wildmenu

" Syntastic
let g:syntastic_cpp_compiler_options = ' -std=c++11'

" Conque Terminal
" let g:ConqueTerm_CloseOnEnd = 1

" Some settings
"set list extends:>,precedes:<

" Invisible character symbol
set listchars=tab:▸\ ,eol:⏎
"set showbreak=➤
set showbreak=…

" let configs
let mapleader = "\\"

" Airline
set t_Co=256
set laststatus=2
let g:airline_powerline_fonts = 1
"let g:airline#extensions#branch#enabled=1
"let g:airline#extensions#hunks#enabled=0

"let g:airline_theme="badwolf"
"let g:airline_section_b = '%{strftime("%c")}'
"let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#tabline#left_sep=' '
"let g:airline#extensions#tabline#left_alt_sep='|'

" Syntastic
"let g:syntastic_error_symbol = "✗"
"let g:syntastic_warning_symbol = "⚠"

" Load custom settings
source ~/.vim/variables.vim
source ~/.vim/functions.vim
source ~/.vim/startup/autocmd.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/color.vim
source ~/.vim/syntax.vim

" filetype on after load startup
if has("autocmd")
	" Enable filetype detection
	filetype plugin on
	"filetype plugin indent on

	" Automatically apply any changes in vimrc
	"autocmd BufWritePost .vimrc tabe $MYVIMRC
endif

" Change buffer without saved
set hidden

" Vertical window split on right side
set splitright

" I use more more modern way to loss data, I use GIT
set nobackup
set noswapfile

" correction
iabbr ture true
iabbr flase false
iabbr fasle false
iabbr recieve receive
iabbr cleant client

" Dictionary words
" set dictionary+=/usr/share/dict/words

" Cursor
if exists('$ITERM_PROFILE')
  if exists('$TMUX')
    let &t_SI = "\<Esc>[5 q"
    let &t_EI = "\<Esc>[0 q"
  else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  endif
end

if has("gui_running")
	source ~/.vim/gvimrc
endif

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:ycm_key_invoke_completion = '<C-Space>'
let g:ycm_cache_omnifunc = 0
let g:ycm_seed_identifiers_with_syntax = 1

"let g:clang_use_library = 1
"let g:clang_library_path = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib'
"let g:clang_complete_auto = 1
"let g:clang_snippets = 1
"let g:clang_snippets_engine = 'ultisnips'
"let g:clang_complete_macros = 1
"let g:clang_user_options = ' -DCLANG_COMPLETE_ONLY'

" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

let g:SuperTabDefaultCompletionType = '<C-n>'

" ES lint
"let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" HTML Lint
let g:syntastic_html_checkers = []

" Flow
" let g:syntastic_javascript_checkers = ['eslint', 'flow']
" let g:syntastic_javascript_flow_exe = 'flow'

" Vim flow
let g:flow#enable = 0

" Test external command
let g:potion_command = "~/.vim/bundle/potion"

" init modes
source ~/.vim/modes/modes.vim
